-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Room_info
CREATE TABLE IF NOT EXISTS room_info (
    room_id BIGINT PRIMARY KEY,
    room_password TEXT NOT NULL,
    topic TEXT NOT NULL,
    include_non_see BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. Room_items
CREATE TABLE IF NOT EXISTS room_items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT REFERENCES room_info(room_id) ON DELETE CASCADE,
    item_name TEXT NOT NULL,
    order_index INT NOT NULL
);

-- 3. Participant_info
CREATE TABLE IF NOT EXISTS participant_info (
    participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT REFERENCES room_info(room_id) ON DELETE CASCADE,
    nick_name TEXT NOT NULL,
    email TEXT NOT NULL,
    submitted_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(room_id, nick_name)
);

-- 4. Participant_answer
CREATE TABLE IF NOT EXISTS participant_answer (
    answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT REFERENCES participant_info(participant_id) ON DELETE CASCADE,
    room_id BIGINT REFERENCES room_info(room_id) ON DELETE CASCADE,
    item_id BIGINT REFERENCES room_items(item_id) ON DELETE CASCADE,
    score INT -- NULLABLE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_room_created_at ON room_info(created_at);
CREATE INDEX IF NOT EXISTS idx_answer_room_id ON participant_answer(room_id);
